language: ruby
branches:
  only:
    - master
rvm:
  - 1.9.3
# uncomment this line if your project needs to run something other than `rake`:
script: bundle exec rspec
before_install:
  - sudo apt-get update -qq
  - export HEADERS=`uname -a`
  - sudo apt-get install dkms build-essential ${HEADERS}
  - wget http://download.virtualbox.org/virtualbox/4.2.10/virtualbox-4.2_4.2.10-84104~Ubuntu~precise_i386.deb ~/VirtualBox.deb
  - sudo dpkg -i ~/VirtualBox.deb
  - vagrant up
